[[redirects]]
from = "https://dev-spazee.netlify.com/*"
to = "https://dev.spazee.co.id/:splat"
status = 301
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false


[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "SAMEORIGIN"
X-Robots-Tag = "index, follow"
